spring:
  application:
    name: webflux-patterns

logging:
  level:
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG

resilience4j.circuitbreaker:
  instances:
    review-service:
      slidingWindowType: COUNT_BASED #TIME_BASED // COUNT_BASED
      slidingWindowSize: 4
      minimumNumberOfCalls: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
        - java.util.concurrent.TimeoutException

sec01:
  review:
    service: http://localhost:7070/sec01/review/
  promotion:
    service: http://localhost:7070/sec01/promotion/
  product:
    service: http://localhost:7070/sec01/product/

sec02:
  delta:
    service: http://localhost:7070/sec02/delta/
  jetblue:
    service: http://localhost:7070/sec02/jetblue/
  frontier:
    service: http://localhost:7070/sec02/frontier/

sec03:
  product:
    service: http://localhost:7070/sec03/product/
  user:
    service: http://localhost:7070/sec03/user/
  inventory:
    service: http://localhost:7070/sec03/inventory/
  shipping:
    service: http://localhost:7070/sec03/shipping/

sec04:
  product:
    service: http://localhost:7070/sec04/product/
  user:
    service: http://localhost:7070/sec04/user/
  inventory:
    service: http://localhost:7070/sec04/inventory/
  shipping:
    service: http://localhost:7070/sec04/shipping/

sec05:
  car:
    service: http://localhost:7070/sec05/car/reserve
  room:
    service: http://localhost:7070/sec05/room/reserve

sec06:
  review:
    service: http://localhost:7070/sec06/review/
  product:
    service: http://localhost:7070/sec06/product/

sec07:
  review:
    service: http://localhost:7070/sec07/review/
  product:
    service: http://localhost:7070/sec07/product/

sec08:
  review:
    service: http://localhost:7070/sec08/review/
  product:
    service: http://localhost:7070/sec08/product/