spring:
  application:
    name: webflux-patterns

sec01:
  review:
    service: http://localhost:7070/sec01/review/
  promotion:
    service: http://localhost:7070/sec01/promotion/
  product:
    service: http://localhost:7070/sec01/product/

sec02:
  delta:
    service: http://localhost:7070/sec02/delta/
  jetblue:
    service: http://localhost:7070/sec02/jetblue/
  frontier:
    service: http://localhost:7070/sec02/frontier/

sec03:
  product:
    service: http://localhost:7070/sec03/product/
  user:
    service: http://localhost:7070/sec03/user/
  inventory:
    service: http://localhost:7070/sec03/inventory/
  shipping:
    service: http://localhost:7070/sec03/shipping/